name: Feature Request
description: Suggest an idea for Study Library Manager
title: "[FEATURE] "
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! 🚀

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: Ex. I'm always frustrated when [...]

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Simple (UI change, minor functionality)
        - Moderate (new component, algorithm change)
        - Complex (major architecture change, new dependencies)
        - Unsure

  - type: checkboxes
    id: java25-features
    attributes:
      label: Java 25 Integration
      description: Would this feature benefit from Java 25 language features?
      options:
        - label: Could use sealed classes for type safety
        - label: Could benefit from records for data structures
        - label: Could use pattern matching for cleaner code
        - label: Could leverage enhanced performance features
        - label: Not applicable

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples about the feature request here.
      placeholder: Screenshots, mockups, links to similar features in other applications, etc.